#!/bin/bash

. ~/.cache/wal/colors.sh

case $BLOCK_BUTTON in
	1) xbacklight -inc 5 ;;
	2) ~/.scripts/brightness ;;
	3) xbacklight -dec 5 ;;
	4) xbacklight -inc 5 ;;
	5) xbacklight -dec 5 ;;
esac

light="$(xbacklight | sed -e 's/\([0-9]\+\)\..*/\1/g')"
printf " %s%%\n" "$light"
printf " %s%%\n" "$light"
printf "$color4\n"


