#!/bin/bash

. ~/.cache/wal/colors.sh

case $BLOCK_BUTTON in
	1) pamixer --toggle-mute ;;
	3) pavucontrol ;;
	4) pactl set-sink-volume 0 +5% ;;
	5) pactl set-sink-volume 0 -5% ;;
esac

[ "$(pamixer --get-mute)" = "true" ] && printf "\n\n#ff0000" && exit

vol=$(pamixer --get-volume)

icon=""
if [ "$vol" -gt "70" ]; then
	icon=""
elif [ "$vol" -gt "30" ]; then
	icon=""
fi

printf "%s %s\n" $icon $vol
printf "%s %s\n" $icon $vol
printf "$color4\n"
