#!/bin/bash

. ~/.cache/wal/colors.sh

case $BLOCK_BUTTON in
	1) notify-send "IPs:" \
		"Local: $( ip addr show dev wlp4s0 | grep 'inet ' | awk '{print $2}')\n\
Remote: $(curl ipv4.icanhazip.com)"
esac

connection="$(nmcli connection show | awk '/wlp4s0/ {print $1}')"
[[ -z $connection ]] && printf " No Wifi\n\n#ff0000" && exit

conn="$(nmcli connection show | awk '/wlp4s0/ {print $1}')"
printf " %s\n\n" "$conn"
printf "$color4"
