#!/bin/sh

numevts=$(calcurse -Q --days 1 | grep '\->' | wc -l)

case $BLOCK_BUTTON in
	1) if [ "$numevts" -gt "0" ]; then
			notify-send "Events for today:" \
				"$(calcurse -Q --days 1)"
		else
			notify-send "No events today" "" 
		fi ;;

	3) st -e calcurse ;;
esac

printf "%s %s" "$numevts" "$(date '+%b %_d %Y')"
