#!/bin/sh

case $BLOCK_BUTTON in
	1) pamixer --toggle-mute ;;
	3) pavucontrol ;;
	4) pactl set-sink-volume 0 +5% ;;
	5) pactl set-sink-volume 0 -5% ;;
esac

[ "$(pamixer --get-mute)" = "true" ] && printf "<span foreground=\"#7f0000\"></span>" && exit

vol=$(pamixer --get-volume)

icon=""
if [ "$vol" -gt "70" ]; then
	icon=""
elif [ "$vol" -gt "30" ]; then
	icon=""
fi

printf "<span foreground=\"#202066\"> %s %s </span>" "$icon" "$vol"
