#!/bin/sh

# Set the background
wal -i "$1" && notify-send "Set background" "$2"

# Update record of background
echo "$1" > ~/.background

# Restart dunst for colors
/home/brendan/.dwm/dunst_launch.sh &
