#!/bin/bash

wallpaper="$( \
	cat \
		<(find "$HOME/Pictures/wallpapers" -name "*.jpg") \
		<(find "$HOME/Pictures/wallpapers" -name "*.png") \
		<(find "$HOME/Dropbox/Pictures/background" -name "*.jpg") \
		<(find "$HOME/Dropbox/Pictures/background" -name "*.png") \
	| dmenu -n -i -l 20 -p "Which background?" \
)"
[ -z "$wallpaper" ] && exit 1

theme="$(echo -e 'Dark\nLight' | dmenu -n -i -l 2 -p "Select theme: " | tr '[:upper:]' '[:lower:]')"

THEME="$theme" /home/brendan/.scripts/utils/set_background "$wallpaper" "$wallpaper"

