#!/bin/bash

wallpaper="$(
	cat \
		<(find "$HOME/Pictures/wallpapers" -name "*.jpg") \
		<(find "$HOME/Pictures/wallpapers" -name "*.png") \
		<(find "$HOME/Dropbox/Pictures/background" -name "*.jpg") \
		<(find "$HOME/Dropbox/Pictures/background" -name "*.png") \
		| shuf -n 1
)"

/home/brendan/.scripts/utils/set_background "$wallpaper" "$wallpaper"

