#!/bin/sh

device_id="$(pactl list short sinks | awk -F'[ \t.]' '{ print $1 ", " $3 }' | dmenu -n -l 10 -p "Which device? " | cut -d',' -f1)"
[ -z "$device_id" ] && exit 1

volume="$(printf 'toggle mute\n0\n5\n10\n15\n20\n25\n30\n35\n40\n45\n50\n55\n60\n65\n70\n75\n80\n85\n90\n95\n100' | dmenu -n -p "Volume for $device: ")"
[ -z "$volume" ] && exit 1

if [ "$volume" = "toggle mute" ]; then
	pactl set-sink-mute "$device_id" toggle ;
else
	pactl set-sink-volume "$device_id" "$volume"% ;
fi
