#!/bin/bash

wallpaper=$( \
	cat \
		<(find "$HOME/Pictures/wallpapers" -name "*.jpg") \
		<(find "$HOME/Pictures/wallpapers" -name "*.png") \
		<(find "$HOME/Dropbox/Pictures/background" -name "*.jpg") \
		<(find "$HOME/Dropbox/Pictures/background" -name "*.png") \
	| dmenu -n -i -l 20 -p "Which background?" \
)
# wallpaper=$(find "$HOME/Pictures/wallpapers" -name "*.jpg" | dmenu -i -l 30 -p "Which background?")
[ -z "$wallpaper" ] && exit 1

# feh --bg-fill /home/brendan/Pictures/background/$wallpaper
# wal -i "/home/brendan/Dropbox/Pictures/background/$wallpaper"
# echo "/home/brendan/Dropbox/Pictures/background/$wallpaper" > ~/.background
wal -i "$wallpaper" && notify-send "Set background" "$wallpaper"
echo "$wallpaper" > ~/.background

# Update i3blocks
# pkill -RTMIN+5 i3blocks
# pkill -RTMIN+9 i3blocks
# pkill -RTMIN+10 i3blocks
# pkill -RTMIN+1 i3blocks
