#!/bin/sh

layout=$(find ~/.screenlayout/ | awk -F"." '{print $1}' | dmenu -fn monospace:11 -l 5 -p "Layout:")
[ -z "$layout" ] && exit 0

~/.screenlayout/"$layout".sh

feg --bg-fill "$(cat ~/.background)"
